# Generated by Django 4.2.5 on 2023-09-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=40)),
                ('expert_bio', models.CharField(max_length=400)),
                ('expert_location', models.CharField(max_length=100)),
                ('expert_experience', models.IntegerField()),
                ('expert_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('show_case_image', models.ImageField(upload_to='Gig/')),
                ('description', models.TextField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Gig_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=10)),
                ('package_description', models.TextField()),
                ('duration', models.TimeField()),
                ('file_attachment', models.BooleanField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gig')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('user_type', models.CharField(max_length=10)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('last_login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('bank_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bank_details')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gig')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField()),
                ('review_text', models.CharField(max_length=2000)),
                ('review_timestamp', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expert')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gig')),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=1000)),
                ('reply_timestamp', models.DateField(auto_now_add=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expert')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.review')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentlink', models.CharField(max_length=250)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_Status', models.CharField(max_length=15)),
                ('meeting_date_time', models.DateTimeField()),
                ('previous_meeting_date_time', models.DateTimeField()),
                ('meeting_update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expert')),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gig')),
                ('gig_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gig_package')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=1000)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gig')),
            ],
        ),
        migrations.CreateModel(
            name='Expert_Catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expert')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Call_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('private', models.BooleanField()),
                ('meet_image', models.ImageField(upload_to='proof/')),
                ('meeting_text', models.TextField()),
                ('audio', models.FileField(upload_to='proof/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expert')),
            ],
        ),
    ]
