# Generated by Django 4.2.5 on 2023-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='account_no',
            field=models.IntegerField(max_length=18),
        ),
    ]
