# Generated by Django 4.2.5 on 2023-09-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gig_package_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig_package',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
