# Generated by Django 4.2.5 on 2023-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gig_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig_package',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
