# Generated by Django 4.2.5 on 2023-09-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bank_details_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
